from pygments.lexer import RegexLexer
from pygments.token import (Comment, Keyword, Text, Name, String)


class RysGitLexer(RegexLexer):
    builtins = [
        'add',
        'am',
        'apply',
        'archive',
        'bisect',
        'blame',
        'branch',
        'bundle',
        'cat-file',
        'checkout',
        'cherry-pick',
        'citool',
        'clean',
        'clone',
        'commit-tree',
        'commit',
        'config',
        'describe',
        'diff',
        'difftool',
        'fetch',
        'format-patch',
        'fsck',
        'gc',
        'grep',
        'gui',
        'help',
        'init',
        'log',
        'ls-tree',
        'merge',
        'mv',
        'notes',
        'pull',
        'push',
        'read-tree',
        'rebase',
        'reflog',
        'remote',
        'request-pull',
        'rerere',
        'reset',
        'revert',
        'rm',
        'send-email',
        'shortlog',
        'show',
        'show-branch',
        'stash',
        'status',
        'svn',
        'submodule',
        'tag',
        'update-index',
        'update-server-info',
        'write-tree',
    ]
    tokens = {
        'root': [
            (r'#.*', Comment),
            (r'[a-zA-Z][a-zA-Z0-9_\-]*', Keyword, 'args'),
        ],
        'args': [
            (r'[ ]+', Text),
            (r'\n', Text, 'root'),
            ('|'.join(builtins), Keyword),  # Could be a Builtin
            (r'--?\w+', Name.Attribute),
            (r'(\'|").+(\'|")', String),
            (r'\S+', Name),
        ]
    }
