dist: trusty
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
branches:
  only:
    - master
before_install:
  - sudo apt-get install -y python-tox
install:
  - pip install -rrequirements.txt
  - pip install .
script:
  - tox
