dist: trusty
sudo: false
language: python
python:
  - "2.7"
  - "3.5"
branches:
  only:
    - master
install:
  - pip install tox-travis coverage
  - pip install -rrequirements.txt
  - pip install .
script:
  - tox
