dist: trusty
sudo: false
language: python
python:
  - "2.7"
  - "3.5"
matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
branches:
  only:
    - master
install:
  - pip install tox-travis coverage
  - pip install -rrequirements.txt
  - pip install .
script:
  - tox
